version: "3.7"

services:
  db:
    image: postgres:13
    ports:
      - 5435:5432
    volumes:
      - pgdata:/data/postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
